### ISSUE TITLE
mq send bug & some question

### ISSUE THREAD

**Issue by vincentknw** [openTCS/opentcs-commadapter-vda5050#1]
1.when robot failed with some task and reboot,  i cancel the last task in tcs, and start a new task, but tcs nerver send a mqtt msg to the robot, i need to restart the tcs kernel to recover;
2.when robot shut down ,tcs cannot recieve state topic for a long time , but state of robot stay IDLE;
3.when robot recieve a action of location, robot need to know the coordinate x y of location, but according to the doc i need to add a property of parameter.x ，paramater.y to location, is there any convenient way to add x y to action msg

commit :da9ed93

**Comment by swltr** [comment]
@vincentknw When opening an issue here, please...

1. stick to one topic per issue.
2. fill out either the "bug report" or the "feature request" template. Questions should go to the discussion forum.
