### ISSUE TITLE
Common configuration onOpModeChangeDoResetPosition

### ISSUE THREAD

**Issue by maxwang001** [openTCS/opentcs-commadapter-vda5050#11]
## Affected version

The latest commit of [Format code via Spotless](https://github.com/openTCS/opentcs-commadapter-vda5050/commit/0e07ac5d43d5b952281ce259115bec73db662ded)

## Steps to reproduce

1. Setup commadapter.vehicle.vda5050.onOpModeChangeDoResetPosition = AUTOMATIC=false, SEMIAUTOMATIC=false, SERVICE=true, MANUAL=false, TEACHIN=false
2. Change OpMode from 'AUTOMATIC' to 'SERVICE'
3. Nothing change in operationDesk

### Expected behaviour

1. Release the point/path resource for this vehicle or I misunderstand the usage of this configuration?

**Comment by sebo001** [comment]
Hi @maxwang001, so far, we have been unable to reproduce the problem.

Which openTCS baseline version are you using?
Also, which [configuration library](https://www.opentcs.org/docs/5.17/developer/developers-guide/opentcs-developers-guide.html#_application_configuration) are you using?

We tried reproducing the problem with baseline version 5.17.1 and gestalt as the config library but everything worked as expected.
