### ISSUE TITLE
After the parking order is interrupted, the AGV will not proceed with the next transportorder.

### ISSUE THREAD

**Issue by z29591259** [openTCS/opentcs-commadapter-vda5050#12]
## Affected version
OpenTCS Version 5.17.1
VDA5050 Version 0.20

## Steps to reproduce

1. Set kernel config defaultdispatcher.parkIdleVehicles => true
2. Use map with a VDA5050 vehicle , set property "vda5050:maxStepsHorizon"=>2, also with a park point
3. Move AGV to the point leave park point for a long distance that make sure there is enought time to create new order before parking order finish, and wait until kernel send parking order to AGV
4. While AGV is executing park order, use API or OperationDesk to create a transportorder

### Expected behaviour

Parking order should be interrupted, then AGV processes the next transportorder.

### Actual behaviour

After the parking order is interrupted, the AGV remains in the EXECUTING state, and the next transport order remains 'DISPATCHABLE.'

### Additional information

The VDA5050 vehicle we use sends its state along with horizon nodes and edges. When a parking order is interrupted, the vehicle retains only the horizon path and waits for the 'released' transfer to be set to 'true.' Since the `nodeState` is not empty, the [statemapping](https://github.com/openTCS/opentcs-commadapter-vda5050/blob/1126f47a9e4abd68300b0bf59272dad1373206da/src/main/java/org/opentcs/commadapter/vehicle/vda5050/v1_1/StateMappings.java#L66) in commadapter-vda5050 shows as EXECUTING.

However, in TCS, the parking order is marked as completed, and the next transport order is waiting for the vehicle to be in the IDLE state.

Sending a 'cancelOrder' instant action can clear the nodeState and edgeState on the AGV, returning it to the IDLE state and allowing the AGV to resume operation.

**Comment by swltr** [comment]
@z29591259 Confirmed! When checking remaining `nodeState` and `edgeState` entries, the horizon should be ignored.

**Comment by z29591259** [comment]
The following thoughts are provided for your reference. Thank you for confirming the issue.

If, during state mapping, the horizon is ignored and the state is set to IDLE, the AGV might simply be waiting for a resource. Once the resource becomes available, it will continue executing the current transportorder.

I believe the key is ensuring that the AGV recognizes when its order has been stopped. There needs to be a mechanism to clear the horizon when a transportorder is interrupted; otherwise, if the AGV believes the current order is still in progress, it will reject new orders. I'm inclined to use `cancelOrder` instantAction to address this issue.

Currently, my workaround is to have the VDA5050Adapter send a `cancelOrder` instantAction when it detects that the AGV only has horizon nodes and edges left, and the transportorder has already concluded, causing the AGV to return to the IDLE state.
