### ISSUE TITLE
controller should set agv state unkonwn when missing state msg

### ISSUE THREAD

**Issue by vincentknw** [openTCS/opentcs-commadapter-vda5050#3]
## User story / use case
when not recieve state msg from a agv to long; controller should set agv  state UNKNOWN。 
## reason
now controller still remain last state IDLE，agv cannot send disconnect msg sometime.

**Comment by swltr** [comment]
@vincentknw The VDA5050 specification describes a clear indication of whether or not a vehicle is available in the form of the `connection` topic and the vehicle's last will:

* When the vehicle disconnects gracefully, it is supposed to publish `OFFLINE` as its `connectionState`.
* For cases in which the vehicle's connection to the MQTT broker is interrupted unexpectedly, the vehicle is supposed to register a last will that publishes `CONNECTIONBROKEN` as its `connectionState`.

As long as the vehicle adheres to the specification, checking for incoming state messages is neither required by the specification nor necessary.
