### ISSUE TITLE
Can use the model  property VehicleLength when lengthLoaded and lengthUnLoaded properties not set？

### ISSUE THREAD

**Issue by xming4321** [openTCS/opentcs-commadapter-vda5050#4]
## User story / use case
when the properties
vda5050:vehicleLengthLoaded 
vda5050:vehicleLengthUnloaded 
not set, the program will use the default 1000

and then enable the vehicle，it while replace the model property of  length  to1000 .

can it use the vaule of the   model property of  length when the 2 properties are not set?

**Comment by swltr** [comment]
@xming4321 Currently (in version 0.18), the VDA5050 driver does not support this. But it sounds like a useful enhancement for the future.

**Comment by manjushreearadhya2016** [comment]
Hi @xming4321, I am facing difficulty integrating VDA5050 with openTCS. Can you please help me with this?

**Comment by swltr** [comment]
@xming4321 As you may have noticed already, since dd7df5e38c99050326fdd183b1963821146271f6 / version 0.19, the driver will fall back to use the vehicle's length as given in the plant model.
